POST http://localhost:8099/user/insert
Content-Type: application/json

{}

###
POST http://localhost:8099/role/public/test
Content-Type: application/json

{}

###
POST http://localhost:8099/user/public/update
Content-Type: application/json

{}

###
POST http://localhost:8099/user/public/select
Content-Type: application/json

{}

###
