server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 注释 log-impl 停止查询结果SQL日志
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    call-setters-on-nulls: true
  mapper-locations: classpath*:/db-mapper/*.xml